### ISSUE TITLE
Get exposed variables from script

### ISSUE THREAD

**Issue by jtenner** [mmckegg/notevil#26]
I have a project that interprets inline JS like this:

```
$: var key = "val";
```

Is there a way to expose 'key' to a provided context when evaling?

This is what I'm hoping for:

```javascript
var ctx = {};
notevil('let x = 0;', ctx);
console.log(ctx.x);
//0
```

Obviously I could require the developer to return an object with the exposed variable names like this:

```javascript
var code = `
  let x = 10;
  Object({ x }); //expose everything wrapped here
`;
```

I would have to do my own mixin on the `ctx` object and it would be a valid workaround.  It's just more work for my developers.

**Comment by mmckegg** [comment]
This should just work if you just remove the `let` and let it fall back to a global!

```js
var ctx = {};
notevil('x = 0', ctx);
console.log(ctx.x);
```

**Comment by jtenner** [comment]
Interesting. Thank you!  Can I re-use this issue and ask another question?

Will notevil support es2015 syntax natively?  It would be nice not to use babel to transpile JS myself. :)

**Comment by mmckegg** [comment]
Possibly. I haven't had a chance to look into how hard this would be. Would accept a pull request though :smile:

**Comment by jtenner** [comment]
Yeah I don't know how to do this myself.  Just curious if this was in your thoughts.

I love the library and cant wait to use it in my visual novel engine.  Thank you!
