### ISSUE TITLE
UnaryExpression delete

### ISSUE THREAD

**Issue by benzmuircroft** [mmckegg/notevil#27]
I have an example object here that you can use reproduce this error

```
var r=[{
	"_id": "BLOCKS",
	"type": "cache",
	"cache": {
		"0000000000260dfd032cb5bc302a3307fe141c7e505b53214a6b7c1703ab9b6b": {
			"height": 1087605,
			"block": "confirmed-block",
			"from": "blockio_blk"
		},
		"00000000000004e108a232adc26102f18388762f18d459952177f486918bbf3f": {
			"height": 1087607,
			"block": "confirmed-block",
			"from": "blockio_blk"
		},
		"00000000004e2a0b541e5a95f6e714e75dcf89964a69bfc34bf615465ef04a74": {
			"height": 1087606,
			"block": "confirmed-block",
			"from": "blockio_blk"
		},
		"00000000a8fc15b379ab82bf3ad04c92b26995c679596cc52ce47791dc751028": {
			"height": 1087608,
			"block": "confirmed-block",
			"from": "blockio_blk"
		},
		"0000000000000255c45f107736f106a4c56d33bb585b3b6f506f8189dafd1330": {
			"height": 1087609,
			"block": "confirmed-block",
			"from": "blockio_blk"
		},
	}
}];

```

Normal eval works fine:

```
eval('for(var i in r[0].cache){if(r[0].cache[i].height>5){delete r[0].cache[i];}}');
console.log(r);

[ { _id: 'BLOCKS', type: 'cache', cache: {} } ]
```

notevail gets error

`require('notevil')('for(var i in r[0].cache){if(r[0].cache[i].height>5){delete r[0].cache[i];}}',{r:r});`

Error: Unsupported expression: UnaryExpression
    at unsupportedExpression (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:416:13)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:260:27)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:103:16)
    at walkAll (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:61:16)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:79:22)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:161:18)
    at walkAll (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:61:16)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:79:22)
    at walk (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:207:19)
    at walkAll (/var/sentora/hostdata/zadmin/node_modules/notevil/index.js:61:16)

The error object looks like

```
"error": {
				"node": {
					"type": "UnaryExpression",
					"operator": "delete",
					"argument": {
						"type": "MemberExpression",
						"computed": true,
						"object": {
							"type": "MemberExpression",
							"computed": false,
							"object": {
								"type": "MemberExpression",
								"computed": true,
								"object": {
									"type": "Identifier",
									"name": "r"
								},
								"property": {
									"type": "Literal",
									"value": 0
								}
							},
							"property": {
								"type": "Identifier",
								"name": "cache"
							}
						},
						"property": {
							"type": "Identifier",
							"name": "i"
						}
					},
					"prefix": true
				}
```

**Comment by benzmuircroft** [comment]
if I add `case 'delete':return delete val` after line 258 in index.js then the error goes away but the object remains unchanged in this case as the word delete appears zero times in index.js

**Comment by mmckegg** [comment]
The problem is that the `walk` done on [line 253](https://github.com/mmckegg/notevil/blob/master/index.js#L253) only works for `UnaryExpressions`s that modify the value, rather than ones that `delete`. This is because it returns the value at the very end of the expression. 

We'll need a new `walk` function that walks `MemberExpression`s and returns the parent of the final value and then its key, and then use this to run `delete parent[key]`.

This is quite a bit more complicated than it seems on the surface. I guess that's why it was never implemented.

**Comment by mmckegg** [comment]
Okay, figured out how to do this in a fairly simple way. I had forgotten how ASTs work 😆  

Support added in **v1.1.0**! 🎉 

@benzmuircroft thanks for reporting this!

**Comment by benzmuircroft** [comment]
just tested and it works perfectly!
